# Generated by Django 5.2.6 on 2025-11-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('pressureUP', models.IntegerField()),
                ('pressureDOWN', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('sleep_time', models.IntegerField()),
                ('BMI', models.IntegerField()),
            ],
        ),
    ]
